variables:
  PROJECT_NAME: qym
  DEPLOYMENT_NAME: qym
  ENV: "dev"

stages:
  - package

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      variables:
        ENV: "dev"
    - if: '$CI_COMMIT_BRANCH == "qa"'
      variables:
        ENV: "qa"
    - if: '$CI_COMMIT_BRANCH == "preprod"'
      variables:
        ENV: "preprod"
    - if: '$CI_COMMIT_BRANCH == "master"'
      variables:
        ENV: "prod"
    - if: '$CI_COMMIT_BRANCH == "prod"'
      variables:
        ENV: "prod"
    - if: '$CI_COMMIT_BRANCH == "eval"'
      variables:
        ENV: "preprod"
    - when: always

package:
  stage: package
  only:
    refs:
      - dev
      - qa
      - main
      - master
      - eval
  script:
    - source /internet.sh
    - >
      podman build \
        --build-arg BASE_IMAGE=$CUSTOM_BASE_IMAGE \
        -v "$CI_BUILDS_DIR":"$CI_BUILDS_DIR" \
        -t "$REGISTRY"/"$HARBOR_PROJECT"/"$PROJECT_NAME":$ENV-latest \
        --annotation org.opencontainers.image.revision=$ENV-"$CI_COMMIT_SHA" \
        -f docker/Dockerfile
      .
    - podman push --creds "$HARBOR_USERNAME":"$HARBOR_PASSWORD" "$REGISTRY"/"$HARBOR_PROJECT"/"$PROJECT_NAME":$ENV-latest
    - podman image tag "$REGISTRY"/"$HARBOR_PROJECT"/"$PROJECT_NAME":$ENV-latest "$REGISTRY"/"$HARBOR_PROJECT"/"$PROJECT_NAME":$ENV-"$CI_COMMIT_SHORT_SHA"
    - podman push --creds "$HARBOR_USERNAME":"$HARBOR_PASSWORD" "$REGISTRY"/"$HARBOR_PROJECT"/"$PROJECT_NAME":$ENV-"$CI_COMMIT_SHORT_SHA"