"""Partitioned ``spans`` (monthly by run_created_at) with promoted scalar columns.

Instant DDL: the new table is created and swapped in by rename; the old table
becomes ``spans_legacy``. Rows are copied later by the ``migrate_spans``
maintenance job (retention-aware, batched) and ``drop_legacy_spans`` returns the
disk. On a fresh database the empty legacy table is dropped immediately.

Raw-trace retention becomes ``DROP PARTITION`` (services/retention.py). Large
JSON columns use LZ4 TOAST compression on PostgreSQL 14+.
"""

from datetime import datetime, timedelta

import sqlalchemy as sa
from alembic import op

revision = "0053"
down_revision = "0052"
branch_labels = None
depends_on = None

PROMOTED = [
    ("oi_kind", sa.String(20)),
    ("usage_scope", sa.String(20)),
    ("model_name", sa.String(200)),
    ("tool_name", sa.String(200)),
    ("token_total", sa.Integer()),
    ("token_prompt", sa.Integer()),
    ("token_completion", sa.Integer()),
]


def month_start(value: datetime) -> datetime:
    return value.replace(day=1, hour=0, minute=0, second=0, microsecond=0)


def next_month(value: datetime) -> datetime:
    return (value.replace(day=28) + timedelta(days=4)).replace(day=1)


def partition_name(start: datetime) -> str:
    return f"spans_y{start.year:04d}m{start.month:02d}"


def ensure_month_partitions(conn, first: datetime, last: datetime) -> list:
    """Create monthly partitions covering [first, last]; returns names created."""
    created = []
    existing = {
        row[0]
        for row in conn.execute(
            sa.text(
                "SELECT c.relname FROM pg_inherits i JOIN pg_class c ON c.oid = i.inhrelid "
                "WHERE i.inhparent = 'spans'::regclass"
            )
        )
    }
    start = month_start(first)
    stop = month_start(last)
    while start <= stop:
        name = partition_name(start)
        if name not in existing:
            end = next_month(start)
            conn.execute(
                sa.text(
                    f"CREATE TABLE {name} PARTITION OF spans FOR VALUES FROM (:s) TO (:e)"
                ).bindparams(s=start, e=end)
            )
            created.append(name)
        start = next_month(start)
    return created


def upgrade():
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        # SQLite: same columns on the existing table; no partitioning, PK unchanged.
        with op.batch_alter_table("spans") as batch:
            batch.add_column(sa.Column("run_created_at", sa.DateTime(), nullable=False, server_default=sa.text("CURRENT_TIMESTAMP")))
            for name, type_ in PROMOTED:
                batch.add_column(sa.Column(name, type_, nullable=True))
        return

    op.execute(
        sa.text(
            """
            CREATE TABLE spans_v2 (
                id bigint GENERATED BY DEFAULT AS IDENTITY,
                run_created_at timestamp NOT NULL,
                run_id varchar(36) NOT NULL REFERENCES runs(id) ON DELETE CASCADE,
                trace_id varchar(64) NOT NULL,
                span_id varchar(32) NOT NULL,
                parent_span_id varchar(32),
                name varchar(500) NOT NULL,
                kind varchar(20) NOT NULL DEFAULT 'INTERNAL',
                start_time_ns bigint,
                end_time_ns bigint,
                duration_ms double precision,
                status varchar(20) NOT NULL DEFAULT 'UNSET',
                attributes jsonb NOT NULL DEFAULT '{}'::jsonb,
                events jsonb NOT NULL DEFAULT '[]'::jsonb,
                links jsonb NOT NULL DEFAULT '[]'::jsonb,
                oi_kind varchar(20),
                usage_scope varchar(20),
                model_name varchar(200),
                tool_name varchar(200),
                token_total integer,
                token_prompt integer,
                token_completion integer,
                PRIMARY KEY (id, run_created_at),
                CONSTRAINT uq_span_v2 UNIQUE (run_id, span_id, run_created_at)
            ) PARTITION BY RANGE (run_created_at)
            """
        )
    )
    for column in ("attributes", "events", "links"):
        op.execute(sa.text(f"ALTER TABLE spans_v2 ALTER COLUMN {column} SET COMPRESSION lz4"))
    op.execute(sa.text("CREATE INDEX ix_span_v2_run_trace ON spans_v2 (run_id, trace_id)"))
    op.execute(sa.text("CREATE INDEX ix_span_v2_run_scope ON spans_v2 (run_id, usage_scope)"))
    op.execute(sa.text("CREATE TABLE spans_v2_default PARTITION OF spans_v2 DEFAULT"))

    # Legacy table keeps its data under a new name; its index/constraint names
    # are renamed so the new table can own the canonical ones.
    legacy_rows = bind.execute(sa.text("SELECT count(*) FROM (SELECT 1 FROM spans LIMIT 1) s")).scalar()
    op.execute(sa.text("ALTER TABLE spans RENAME TO spans_legacy"))
    op.execute(sa.text("ALTER INDEX IF EXISTS ix_span_run_trace RENAME TO ix_span_legacy_run_trace"))
    op.execute(sa.text("ALTER TABLE spans_legacy RENAME CONSTRAINT uq_span TO uq_span_legacy"))
    op.execute(sa.text("ALTER TABLE spans_legacy RENAME CONSTRAINT spans_pkey TO spans_legacy_pkey"))
    op.execute(sa.text("ALTER SEQUENCE IF EXISTS spans_id_seq RENAME TO spans_legacy_id_seq"))

    op.execute(sa.text("ALTER TABLE spans_v2 RENAME TO spans"))
    op.execute(sa.text("ALTER TABLE spans_v2_default RENAME TO spans_default"))
    op.execute(sa.text("ALTER TABLE spans RENAME CONSTRAINT uq_span_v2 TO uq_span"))
    op.execute(sa.text("ALTER INDEX ix_span_v2_run_trace RENAME TO ix_span_run_trace"))
    op.execute(sa.text("ALTER INDEX ix_span_v2_run_scope RENAME TO ix_span_run_scope"))

    first = bind.execute(sa.text("SELECT min(created_at) FROM runs")).scalar() or datetime.utcnow()
    ensure_month_partitions(bind, first, datetime.utcnow() + timedelta(days=95))

    if not legacy_rows:
        op.execute(sa.text("DROP TABLE spans_legacy"))


def downgrade():
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        with op.batch_alter_table("spans") as batch:
            for name, _ in PROMOTED:
                batch.drop_column(name)
            batch.drop_column("run_created_at")
        return
    has_legacy = bind.execute(sa.text("SELECT to_regclass('spans_legacy') IS NOT NULL")).scalar()
    op.execute(sa.text("DROP TABLE spans CASCADE"))
    if has_legacy:
        op.execute(sa.text("ALTER TABLE spans_legacy RENAME TO spans"))
        op.execute(sa.text("ALTER INDEX IF EXISTS ix_span_legacy_run_trace RENAME TO ix_span_run_trace"))
        op.execute(sa.text("ALTER TABLE spans RENAME CONSTRAINT uq_span_legacy TO uq_span"))
        op.execute(sa.text("ALTER TABLE spans RENAME CONSTRAINT spans_legacy_pkey TO spans_pkey"))
        op.execute(sa.text("ALTER SEQUENCE IF EXISTS spans_legacy_id_seq RENAME TO spans_id_seq"))
    else:
        op.create_table(
            "spans",
            sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
            sa.Column("run_id", sa.String(36), sa.ForeignKey("runs.id"), nullable=False),
            sa.Column("trace_id", sa.String(64), nullable=False),
            sa.Column("span_id", sa.String(32), nullable=False),
            sa.Column("parent_span_id", sa.String(32), nullable=True),
            sa.Column("name", sa.String(500), nullable=False),
            sa.Column("kind", sa.String(20), nullable=False),
            sa.Column("start_time_ns", sa.BigInteger(), nullable=True),
            sa.Column("end_time_ns", sa.BigInteger(), nullable=True),
            sa.Column("duration_ms", sa.Float(), nullable=True),
            sa.Column("status", sa.String(20), nullable=False),
            sa.Column("attributes", sa.dialects.postgresql.JSONB(), nullable=False),
            sa.Column("events", sa.dialects.postgresql.JSONB(), nullable=False),
            sa.Column("links", sa.dialects.postgresql.JSONB(), nullable=False),
            sa.UniqueConstraint("run_id", "span_id", name="uq_span"),
        )
        op.create_index("ix_span_run_trace", "spans", ["run_id", "trace_id"])
